### ISSUE TITLE
Support truthy return from Function-type Request Specification

### ISSUE THREAD

**Issue by craigworrall** [johanhaleby/stub-http#18]
Requirement on such functions is currently:

`(fn [request] <true or false>)`

Can this be relaxed to require a truthy return only?

**Comment by johanhaleby** [comment]
Can you give me an example of when it would be useful so that I understand your use case? :)

**Comment by craigworrall** [comment]
If I want to match /some/long/and/winding/uri, it would be more idiomatic to say:

`(fn [request] (re-find #"winding" (:path request)))`

rather than

`(fn [request] (if (re-find #"winding" (:path request)) true))`

**Comment by johanhaleby** [comment]
Ok, got it! Could you create a PR?

**Comment by johanhaleby** [comment]
Ok, got it! Could you create a PR?
