### ISSUE TITLE
Request matching doesn't check body

### ISSUE THREAD

**Issue by neverfox** [johanhaleby/stub-http#5]
```
(with-routes! 
  {{:path "/y" :content-type "application/json" :body (json/generate-string {:q "something"})}
   {:status 200 :content-type "application/json"
    :body (json/generate-string {:hello "brave new world"})}}
  (clj-http.client/get (str uri "/y") {:body (json/generate-string {:q "something else"})}))
```
This works when I wouldn't expect it to. That also make is impossible to have several routes that have the same path but different request bodies without error. I realize that it's not standard to do GET with a body, but some APIs (e.g. Elasticsearch) work that way. Besides, it doesn't make a difference if I use POST.

**Comment by johanhaleby** [comment]
`:body` in the request specification is ignored and not used/supported (pull requests are welcome :)). If you use a function as request specification (see docs [here](https://github.com/johanhaleby/stub-http/wiki/routes#request-specification)) you can manually extract the body and use whatever logic you wish.

**Comment by neverfox** [comment]
I tried the function approach, but if the method is GET but you're still sending a body (as with Elasticsearch requests), then `:body` simply isn't on the request map at all, so there's nothing I could do with it even if I wanted to. So I think this will require a PR. I'll see what I can do.

**Comment by johanhaleby** [comment]
Oh ok, then it might be quite tricky since stub-http is using [nano-httpd](https://github.com/NanoHttpd/nanohttpd) which (to the best of my knowledge) is the one to blame for excluding the body in this case.

**Comment by jonassvalin** [comment]
I've added a PR for this https://github.com/johanhaleby/stub-http/pull/13

**Comment by johanhaleby** [comment]
@jonassvalin Thanks a lot, really cool! I'll try to make a new release.

**Comment by Limess** [comment]
Hey, I just saw this and I think it was released and can be closed now? 🎉

**Comment by jonassvalin** [comment]
@Limess it was indeed merged, so should be fine to close

**Comment by johanhaleby** [comment]
Thanks for pointing out :)
